### ISSUE TITLE
Publish plugin repo assets to Modsurfer

### ISSUE THREAD

**Issue by neuronicnobody** [extism/plugins#5]
With the launch of Modsurfer Public, we should serve all example Extism plugins (such as those on the Quickstart guides) from Modsurfer. As such, the plugins repo should publish all builds to Modsurfer instead of the assets directory

This should just involve changing the corresponding GH action to push to Modsurfer instead of the assets directory

**Comment by bhelx** [comment]
I'm unsure if we still want to do this because modsurfer is content addressable storage only at the moment. The nice thing about having github releases is we can get the "latest" plugin by name like: `https://github.com/extism/plugins/releases/latest/download/count_vowels.wasm`

I could be wrong though, so let's re-open if this changes or we do want to do this.
